// <auto-generated />
using FlightInfoApp.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlightInfoApp.Migrations
{
    [DbContext(typeof(FlightInfoContext))]
    [Migration("20190101162325_FlightInfoApp.Model.FlightInfoContext")]
    partial class FlightInfoAppModelFlightInfoContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FlightInfoApp.Model.FlightInfo", b =>
                {
                    b.Property<int>("FlightID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FlightNo");

                    b.Property<string>("FromAirport");

                    b.Property<string>("ToAirport");

                    b.HasKey("FlightID");

                    b.ToTable("FlightInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
